# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Fall 2018/CS151/CS151-Verilog-Project/CS151_Processor/CS151_Processor.cache/wt} [current_project]
set_property parent.project_path {D:/Fall 2018/CS151/CS151-Verilog-Project/CS151_Processor/CS151_Processor.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Fall 2018/CS151/CS151-Verilog-Project/CS151_Processor/CS151_Processor.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/Fall 2018/CS151/CS151-Verilog-Project/CS151_Processor/CS151_Processor.srcs/sources_1/new/ALU32bit.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/modules/CS151_MOV/CS151_MOV.srcs/sources_1/new/CS151_MOV.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/modules/OR/OR.srcs/sources_1/new/CS151_Or.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/modules/SHIFT/SHIFT.srcs/sources_1/new/CS151_SHIFT.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/modules/XOR/XOR.srcs/sources_1/new/CS151_XOR.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/modules/NOT/NOT.srcs/sources_1/new/CS151_not.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/modules/CS151-processor/CS151-processor.srcs/sources_1/new/Controller.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/modules/2-1 mux/2-1 mux.srcs/sources_1/new/Mux2_1.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/modules/CS151-processor/CS151-processor.srcs/sources_1/new/RegFile.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/modules/adder/adder.srcs/sources_1/new/adder.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/modules/And/And.srcs/sources_1/new/and.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/CS151_Processor/CS151_Processor.srcs/sources_1/new/insMem.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/modules/Sign_extension/Sign_extension.srcs/sources_1/new/sign_extend.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/modules/subtractor/subtractor.srcs/sources_1/new/sub.v}
  {D:/Fall 2018/CS151/CS151-Verilog-Project/CS151_Processor/CS151_Processor.srcs/sources_1/new/CS151-Processor.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top CS151_Processor -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CS151_Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CS151_Processor_utilization_synth.rpt -pb CS151_Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
